version: '2'
services:
  keycloak:
    image: 'docker.io/skillix/keycloak'
    ports:
      - '8080:8080'
    volumes:
      - './secrets:/tmp'
    environment:
      - KEYCLOAK_USER_FILE=/tmp/keycloak-admin-user.txt
      - KEYCLOAK_PASSWORD_FILE=/tmp/keycloak-admin-password.txt
      - BD_USER_FILE=/tmp/keycloak-db-user.txt
      - DB_PASSWORD_FILE=/tmp/keycloak-db-password.txt
      - DB_VENDOR=h2
#      - DB_VENDOR=postgres
#      - DB_ADDR=skillix_un
      - DB_PORT=5432
      - DB_DATABASE=skillix_iam_db
      - DB_SCHEMA=skillix
