docker run \
-e KEYCLOAK_USER=nana0chimi \
-e KEYCLOAK_PASSWORD=4j3ymfnUL6HuequfIxvhN8zwe7utgp \
-e DB_VENDOR=h2 \
-e DB_PORT=5432 \
-e DB_DATABASE=skillix_iam_db \
-e DB_SCHEMA=skillix \
-e DB_USER=skillix0un \
-e DB_PASSWORD=skillix_pw \
-p 8080:8080 \
-d  skillix/keycloak:0.0.1